/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as ApiAlertsTelegramRouteImport } from './routes/api.alerts.telegram'
import { Route as ApiPublicHooksRuijiePollRouteImport } from './routes/api/public/hooks/ruijie-poll'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAlertsTelegramRoute = ApiAlertsTelegramRouteImport.update({
  id: '/api/alerts/telegram',
  path: '/api/alerts/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRuijiePollRoute =
  ApiPublicHooksRuijiePollRouteImport.update({
    id: '/api/public/hooks/ruijie-poll',
    path: '/api/public/hooks/ruijie-poll',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/admin/audit': typeof AdminAuditRoute
  '/api/alerts/telegram': typeof ApiAlertsTelegramRoute
  '/api/public/hooks/ruijie-poll': typeof ApiPublicHooksRuijiePollRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/admin/audit': typeof AdminAuditRoute
  '/api/alerts/telegram': typeof ApiAlertsTelegramRoute
  '/api/public/hooks/ruijie-poll': typeof ApiPublicHooksRuijiePollRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/admin/audit': typeof AdminAuditRoute
  '/api/alerts/telegram': typeof ApiAlertsTelegramRoute
  '/api/public/hooks/ruijie-poll': typeof ApiPublicHooksRuijiePollRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/forgot-password'
    | '/login'
    | '/admin/audit'
    | '/api/alerts/telegram'
    | '/api/public/hooks/ruijie-poll'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/forgot-password'
    | '/login'
    | '/admin/audit'
    | '/api/alerts/telegram'
    | '/api/public/hooks/ruijie-poll'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/forgot-password'
    | '/login'
    | '/admin/audit'
    | '/api/alerts/telegram'
    | '/api/public/hooks/ruijie-poll'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ApiAlertsTelegramRoute: typeof ApiAlertsTelegramRoute
  ApiPublicHooksRuijiePollRoute: typeof ApiPublicHooksRuijiePollRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/alerts/telegram': {
      id: '/api/alerts/telegram'
      path: '/api/alerts/telegram'
      fullPath: '/api/alerts/telegram'
      preLoaderRoute: typeof ApiAlertsTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ruijie-poll': {
      id: '/api/public/hooks/ruijie-poll'
      path: '/api/public/hooks/ruijie-poll'
      fullPath: '/api/public/hooks/ruijie-poll'
      preLoaderRoute: typeof ApiPublicHooksRuijiePollRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ApiAlertsTelegramRoute: ApiAlertsTelegramRoute,
  ApiPublicHooksRuijiePollRoute: ApiPublicHooksRuijiePollRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
