/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as SchoolsRouteImport } from './routes/schools'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReportRouteImport } from './routes/report'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherTeacherIndexRouteImport } from './routes/teacher/teacher.index'
import { Route as TeacherTeacherLoginRouteImport } from './routes/teacher/teacher.login'
import { Route as ApiAlertsTelegramRouteImport } from './routes/api.alerts.telegram'
import { Route as ApiPublicHooksRuijiePollRouteImport } from './routes/api/public/hooks/ruijie-poll'

const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsRoute = SchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherTeacherIndexRoute = TeacherTeacherIndexRouteImport.update({
  id: '/teacher/teacher/',
  path: '/teacher/teacher/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherTeacherLoginRoute = TeacherTeacherLoginRouteImport.update({
  id: '/teacher/teacher/login',
  path: '/teacher/teacher/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlertsTelegramRoute = ApiAlertsTelegramRouteImport.update({
  id: '/api/alerts/telegram',
  path: '/api/alerts/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRuijiePollRoute =
  ApiPublicHooksRuijiePollRouteImport.update({
    id: '/api/public/hooks/ruijie-poll',
    path: '/api/public/hooks/ruijie-poll',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/report': typeof ReportRoute
  '/reports': typeof ReportsRoute
  '/schools': typeof SchoolsRoute
  '/tickets': typeof TicketsRoute
  '/api/alerts/telegram': typeof ApiAlertsTelegramRoute
  '/teacher/teacher/login': typeof TeacherTeacherLoginRoute
  '/teacher/teacher/': typeof TeacherTeacherIndexRoute
  '/api/public/hooks/ruijie-poll': typeof ApiPublicHooksRuijiePollRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/report': typeof ReportRoute
  '/reports': typeof ReportsRoute
  '/schools': typeof SchoolsRoute
  '/tickets': typeof TicketsRoute
  '/api/alerts/telegram': typeof ApiAlertsTelegramRoute
  '/teacher/teacher/login': typeof TeacherTeacherLoginRoute
  '/teacher/teacher': typeof TeacherTeacherIndexRoute
  '/api/public/hooks/ruijie-poll': typeof ApiPublicHooksRuijiePollRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/report': typeof ReportRoute
  '/reports': typeof ReportsRoute
  '/schools': typeof SchoolsRoute
  '/tickets': typeof TicketsRoute
  '/api/alerts/telegram': typeof ApiAlertsTelegramRoute
  '/teacher/teacher/login': typeof TeacherTeacherLoginRoute
  '/teacher/teacher/': typeof TeacherTeacherIndexRoute
  '/api/public/hooks/ruijie-poll': typeof ApiPublicHooksRuijiePollRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/audit'
    | '/forgot-password'
    | '/login'
    | '/report'
    | '/reports'
    | '/schools'
    | '/tickets'
    | '/api/alerts/telegram'
    | '/teacher/teacher/login'
    | '/teacher/teacher/'
    | '/api/public/hooks/ruijie-poll'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/audit'
    | '/forgot-password'
    | '/login'
    | '/report'
    | '/reports'
    | '/schools'
    | '/tickets'
    | '/api/alerts/telegram'
    | '/teacher/teacher/login'
    | '/teacher/teacher'
    | '/api/public/hooks/ruijie-poll'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/audit'
    | '/forgot-password'
    | '/login'
    | '/report'
    | '/reports'
    | '/schools'
    | '/tickets'
    | '/api/alerts/telegram'
    | '/teacher/teacher/login'
    | '/teacher/teacher/'
    | '/api/public/hooks/ruijie-poll'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuditRoute: typeof AuditRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ReportRoute: typeof ReportRoute
  ReportsRoute: typeof ReportsRoute
  SchoolsRoute: typeof SchoolsRoute
  TicketsRoute: typeof TicketsRoute
  ApiAlertsTelegramRoute: typeof ApiAlertsTelegramRoute
  TeacherTeacherLoginRoute: typeof TeacherTeacherLoginRoute
  TeacherTeacherIndexRoute: typeof TeacherTeacherIndexRoute
  ApiPublicHooksRuijiePollRoute: typeof ApiPublicHooksRuijiePollRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools': {
      id: '/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof SchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/teacher/': {
      id: '/teacher/teacher/'
      path: '/teacher/teacher'
      fullPath: '/teacher/teacher/'
      preLoaderRoute: typeof TeacherTeacherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/teacher/login': {
      id: '/teacher/teacher/login'
      path: '/teacher/teacher/login'
      fullPath: '/teacher/teacher/login'
      preLoaderRoute: typeof TeacherTeacherLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alerts/telegram': {
      id: '/api/alerts/telegram'
      path: '/api/alerts/telegram'
      fullPath: '/api/alerts/telegram'
      preLoaderRoute: typeof ApiAlertsTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ruijie-poll': {
      id: '/api/public/hooks/ruijie-poll'
      path: '/api/public/hooks/ruijie-poll'
      fullPath: '/api/public/hooks/ruijie-poll'
      preLoaderRoute: typeof ApiPublicHooksRuijiePollRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuditRoute: AuditRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ReportRoute: ReportRoute,
  ReportsRoute: ReportsRoute,
  SchoolsRoute: SchoolsRoute,
  TicketsRoute: TicketsRoute,
  ApiAlertsTelegramRoute: ApiAlertsTelegramRoute,
  TeacherTeacherLoginRoute: TeacherTeacherLoginRoute,
  TeacherTeacherIndexRoute: TeacherTeacherIndexRoute,
  ApiPublicHooksRuijiePollRoute: ApiPublicHooksRuijiePollRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
